[package]
name = "cow-interpreter"
version = "0.1.0"
authors = ["greg-el <gr3gl@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "cow-interpreter"
path = "src/lib.rs"
